language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages:
    - gfortran

matrix:
  include:
  - os: linux
  - os: osx
    before_install: 
    - brew update > /dev/null
    - brew install gcc > /dev/null
  - os: windows
    install: mingw32-make
    script: mingw32-make test

install: make

script: make test
